export interface Review{
id: number,
productId: number,
author: string,
text: string,
rating: number
}



export const reviews : Review[]=[
{
id: 1,
productId: 1,
author: "Michael K.",
text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod ipsa quisquam iste quibusdam nihil aperiam, aut quae error optio nemo ab saepe labore! Eligendi beatae asperiores repudiandae voluptates id cum.", 
rating: 5,
},
{id: 2,
    productId: 4,
    author: "Sarah M.",
    text: "I'm blown away by the quality and style of the clothes I received from Shop.co. From casual wear to elegant dresses, every piece I've bought has exceeded my expectations.",
    rating: 5
},
{
    id:3 ,
    productId: 12,
    author: "Alex K.",
    text:"Finding clothes that align with my personal style used to be a challenge until I discovered Shop.co. The range of options they offer is truly remarkable, catering to a variety of tastes and occasions." ,
    rating: 4.5

},
{
id: 4,
    productId: 7,
    author: "James L.",
    text: "As someone who's always on the lookout for unique fashion pieces, I'm thrilled to have stumbled upon Shop.co. The selection of clothes is not only diverse but also on-point with the latest trends.",
    rating: 5
},
{id: 5,
    productId: 4,
    author: "Samantha D.",
    text: "I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt.",
    rating: 4.5},

    {id:6 ,
    productId:1,
    author: "Ethan R.",
    text: "This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt.",
    rating: 5},
    {id: 7,
    productId: 4,
    author:"Liam K." ,
    text: "This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion.",
    rating: 4},
    {id: 8,
    productId:11 ,
    author: "Alex M.",
    text: "The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me.",
    rating: 5},
    {id: 9,
    productId:12 ,
    author:"Olivia P." ,
    text:"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out." ,
    rating: 5},
    {id: 10,
    productId:13 ,
    author: "Ava H." ,
    text: "I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter.",
    rating: 4.5},
    {id: 11,
    productId: 13,
    author: "Alex T.",
    text: "I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter.",
    rating: 4.5},
  {id: 12 ,
    productId: 10,
    author: "Milli O.",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae odit perspiciatis dicta quas quam nesciunt repudiandae consectetur tenetur voluptatem aspernatur. Rem laudantium delectus nihil dolore ipsum rerum expedita obcaecati at.", 
    rating: 4.5},
      {id: 13 ,
    productId: 7,
    author: "Alexa S.",
    text: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor ducimus inventore omnis pariatur? Nobis rerum sequi maiores! Earum eius, nulla amet enim asperiores, debitis odio quas dolorem consequatur quo sequi.",
    rating: 4.5},
      {id: 14 ,
    productId: 5,
    author: "Alex T.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 4.5},
        {id: 15 ,
    productId: 5,
    author: "Emma S.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 4},
      {id: 16 ,
    productId: 3,
    author: "George W.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 4},
      {id: 17 ,
    productId: 9,
    author: "Mike G.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 4.5},
      {id: 18 ,
    productId: 2,
    author: "Evan G.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 4},
      {id: 19 ,
    productId: 6,
    author: "Milla K.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 5},
      {id: 20 ,
    productId: 13,
    author: "Will S.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 4.5},
  {id: 21 ,
    productId: 11,
    author: "vik S.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 5},
      {id: 22 ,
    productId: 8,
    author: "Killian M.",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur repellendus natus ipsum tempore libero doloribus recusandae rerum distinctio! Itaque, expedita. Suscipit est quae ex architecto? At ad molestias consequuntur alias.", 
    rating: 4}

]

